spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: ${MONGODB_PASSWORD}
      database: expensemanager
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
